branch-defaults:
  master:
    environment: Shpred-env
environment-defaults:
  Shpred-env:
    branch: null
    repository: null
global:
  application_name: Shpred
  default_ec2_keyname: null
  default_platform: arn:aws:elasticbeanstalk:eu-west-1::platform/Passenger with Ruby
    2.4 running on 64bit Amazon Linux/2.5.0
  default_region: eu-west-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  sc: git
  workspace_type: Application
