default: &default
  access_key_id: <%= ENV["AWS_ACCESS_KEY_ID"] %>
  secret_access_key: <%= ENV["AWS_SECRET_KEY"] %>
  bucket: <%= ENV["S3_BUCKET"] %>
development:
  <<: *default
test:
  <<: *default
production:
  <<: *default