default: &default
  adapter: mysql2
  encoding: utf8
  database: shpred
  pool: 5
  username: root
  password:

development:
  <<: *default

test:
  <<: *default
  database: shpred_test

production:
  <<: *default
